export default [
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Easy bouldering",
    distance: 0.0,
    moving_time: 3600,
    elapsed_time: 3600,
    total_elevation_gain: 0,
    type: "RockClimbing",
    sport_type: "RockClimbing",
    id: 10258557883,
    start_date: "2023-11-21T17:00:00Z",
    start_date_local: "2023-11-21T18:00:00Z",
    timezone: "(GMT+01:00) Europe/Budapest",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 4,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10258557883",
      summary_polyline: "",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [],
    end_latlng: [],
    average_speed: 0.0,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    upload_id: null,
    external_id: null,
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Last Kraków hotel swim 😔",
    distance: 1700.0,
    moving_time: 2160,
    elapsed_time: 2160,
    total_elevation_gain: 0,
    type: "Swim",
    sport_type: "Swim",
    id: 10249960132,
    start_date: "2023-11-20T08:48:00Z",
    start_date_local: "2023-11-20T09:48:00Z",
    timezone: "(GMT+01:00) Europe/Budapest",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 4,
    comment_count: 2,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10249960132",
      summary_polyline: "",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [],
    end_latlng: [],
    average_speed: 0.787,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    upload_id: null,
    external_id: null,
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 1,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Kraków hotel swim 🫛",
    distance: 1025.0,
    moving_time: 1320,
    elapsed_time: 1320,
    total_elevation_gain: 0,
    type: "Swim",
    sport_type: "Swim",
    id: 10247609968,
    start_date: "2023-11-19T18:00:58Z",
    start_date_local: "2023-11-19T19:00:58Z",
    timezone: "(GMT+01:00) Europe/Budapest",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 4,
    comment_count: 3,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10247609968",
      summary_polyline: "",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [],
    end_latlng: [],
    average_speed: 0.777,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    upload_id: null,
    external_id: null,
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 1,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Kraków hotel swim",
    distance: 1350.0,
    moving_time: 1800,
    elapsed_time: 1800,
    total_elevation_gain: 0,
    type: "Swim",
    sport_type: "Swim",
    id: 10240759383,
    start_date: "2023-11-18T16:00:36Z",
    start_date_local: "2023-11-18T17:00:36Z",
    timezone: "(GMT+01:00) Europe/Budapest",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 4,
    comment_count: 2,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10240759383",
      summary_polyline: "",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [],
    end_latlng: [],
    average_speed: 0.75,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    upload_id: null,
    external_id: null,
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Kraków hotel run",
    distance: 5000.0,
    moving_time: 2100,
    elapsed_time: 2100,
    total_elevation_gain: 0,
    type: "Run",
    sport_type: "Run",
    workout_type: 0,
    id: 10237544532,
    start_date: "2023-11-18T06:50:00Z",
    start_date_local: "2023-11-18T07:50:00Z",
    timezone: "(GMT+01:00) Europe/Budapest",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 2,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10237544532",
      summary_polyline: "",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [],
    end_latlng: [],
    average_speed: 2.381,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    upload_id: null,
    external_id: null,
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 1,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Bouldering",
    distance: 0.0,
    moving_time: 10800,
    elapsed_time: 10800,
    total_elevation_gain: 0,
    type: "RockClimbing",
    sport_type: "RockClimbing",
    id: 10225025208,
    start_date: "2023-11-15T15:15:40Z",
    start_date_local: "2023-11-15T16:15:40Z",
    timezone: "(GMT+01:00) Europe/Budapest",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 3,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10225025208",
      summary_polyline: "",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [],
    end_latlng: [],
    average_speed: 0.0,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    upload_id: null,
    external_id: null,
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Bouldering",
    distance: 0.0,
    moving_time: 5400,
    elapsed_time: 5400,
    total_elevation_gain: 0,
    type: "RockClimbing",
    sport_type: "RockClimbing",
    id: 10217832273,
    start_date: "2023-11-14T15:00:59Z",
    start_date_local: "2023-11-14T16:00:59Z",
    timezone: "(GMT+01:00) Europe/Budapest",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 4,
    comment_count: 5,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10217832273",
      summary_polyline: "",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [],
    end_latlng: [],
    average_speed: 0.0,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    upload_id: null,
    external_id: null,
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 2,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Outdoor climbing at Vogerlwandl",
    distance: 0.0,
    moving_time: 12600,
    elapsed_time: 12600,
    total_elevation_gain: 0,
    type: "RockClimbing",
    sport_type: "RockClimbing",
    id: 10206981640,
    start_date: "2023-11-12T11:00:00Z",
    start_date_local: "2023-11-12T12:00:00Z",
    timezone: "(GMT+01:00) Europe/Budapest",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 6,
    comment_count: 3,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10206981640",
      summary_polyline: "",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [],
    end_latlng: [],
    average_speed: 0.0,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    upload_id: null,
    external_id: null,
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 3,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Bouldering",
    distance: 0.0,
    moving_time: 3600,
    elapsed_time: 3600,
    total_elevation_gain: 0,
    type: "RockClimbing",
    sport_type: "RockClimbing",
    id: 10200340465,
    start_date: "2023-11-11T14:00:00Z",
    start_date_local: "2023-11-11T15:00:00Z",
    timezone: "(GMT+01:00) Europe/Budapest",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 6,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10200340465",
      summary_polyline: "",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [],
    end_latlng: [],
    average_speed: 0.0,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    upload_id: null,
    external_id: null,
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 1,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Boulder and ride 💪",
    distance: 14169.5,
    moving_time: 2511,
    elapsed_time: 2629,
    total_elevation_gain: 32.6,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 0,
    id: 10194928078,
    start_date: "2023-11-10T17:00:41Z",
    start_date_local: "2023-11-10T18:00:41Z",
    timezone: "(GMT+01:00) Europe/Vienna",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 13,
    kudos_count: 4,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10194928078",
      summary_polyline:
        "wraeHqw~bBm@tAOCS]S}@_@e@mAyD?QSw@BF[AEi@_@mAgAmBu@yBaDcGiAwCkDcHqAaDc@s@aBkAu@ILu@PcDf@qCPWRaAt@cBXg@~CqEbAkBJaAG}@yAcCc@]yDcGg@e@k@eAsAcB}DuBiDyCs@OIQ@k@eAc@o@y@W}@mBgEGWsAOc@_AoGmIs@a@e@m@Ic@cBmAm@s@CSPq@g@qAMw@cAkBwAuDMm@i@wAOg@UYCs@[e@kDwIgCgEu@gAeCaCO_@WUqGgE_@a@uAi@gBYc@]q@Ie@J[Ym@_AM?Og@Es@\\gCSw@@U}@s@kBKtAiCR{@j@}A`@w@AWRMH[EYNc@B]AW]sAF_@Go@`@uAC{@HIPGTc@PiAjMyM?[i@qA?Qy@eAZJ?KHDEBBQQKQi@uAwBsBsAcA}@OWKyAWsA[Ym@iAwBiA}DMOi@Jo@[@PDK}ARz@q@_ASoDSg@UeBgAyAeA_@i@}@Ge@o@Sc@eAs@i@[u@Q?Ws@MEY{@k@YMo@EB@W[IMNBRNQEoAi@cAu@aA?qAaA{@M_@AQr@kAEg@eAgBUOOi@qAq@u@i@Aa@S]NVGFMSFa@MOAW{@{@a@u@eAAaAa@_A`@m@l@g@dAe@^Oh@[?KXw@`AY`AOJUD{@s@e@K_@Dk@z@[AA]^gAHeAo@iBCc@NW]kBFOGy@Vs@Hs@OI@OOUOy@gAWSNe@sA@LMN{JmSeG}CiAICNL@CXAaALCBOc@qA?e@c@gCqAw@s@@m@qAW?gAi@Wg@e@IFDQ]]IYm@i@]Su@OSWqBQs@?eBEMCUH{@E[VoAASSk@u@w@q@oAMw@Ha@OmAGuBFk@L_FAw@`@i@LwCPi@@YIQsBYi@o@lBqEv@gDAU~@gELgAv@gCTQIMPUh@_Ch@{E|A}Q?y@f@gGLwBMc@a@EBs@o@]A_BQwAw@{@Ee@QWg@c@Eg@cAcA{As@{AoBUi@Nj@a@_AyAgBw@o@BL[_AeJuG?_@NSxCwD?YSM_@yBBsBJo@xAoDvAoJHeAQeAyFoBmIaDiAMuDkBgAUMYKoA\\eGJc@dAuL\\}BDiAb@_Cp@eH`@eHNi@z@yIN}@\\q@Lq@XsCXaA@e@",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [48.18158729933202, 16.385258976370096],
    end_latlng: [48.224812941625714, 16.50185133330524],
    average_speed: 5.643,
    max_speed: 18.861,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 202.5,
    elev_low: 155.4,
    upload_id: 10918672485,
    upload_id_str: "10918672485",
    external_id: "59F2D7CB-F09C-4B50-B7FA-D86186B45C15-activity.fit",
    from_accepted_tag: false,
    pr_count: 3,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Bouldering",
    distance: 0.0,
    moving_time: 10800,
    elapsed_time: 10800,
    total_elevation_gain: 0,
    type: "RockClimbing",
    sport_type: "RockClimbing",
    id: 10194931185,
    start_date: "2023-11-10T14:00:56Z",
    start_date_local: "2023-11-10T15:00:56Z",
    timezone: "(GMT+01:00) Europe/Budapest",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 3,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10194931185",
      summary_polyline: "",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [],
    end_latlng: [],
    average_speed: 0.0,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    upload_id: null,
    external_id: null,
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Bouldering with 7A send",
    distance: 0.0,
    moving_time: 12600,
    elapsed_time: 12600,
    total_elevation_gain: 0,
    type: "RockClimbing",
    sport_type: "RockClimbing",
    id: 10184345030,
    start_date: "2023-11-08T14:15:00Z",
    start_date_local: "2023-11-08T15:15:00Z",
    timezone: "(GMT+01:00) Europe/Budapest",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 5,
    comment_count: 3,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10184345030",
      summary_polyline: "",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [],
    end_latlng: [],
    average_speed: 0.0,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    upload_id: null,
    external_id: null,
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Sightseeing ride",
    distance: 18669.5,
    moving_time: 5750,
    elapsed_time: 8150,
    total_elevation_gain: 48.5,
    type: "Ride",
    sport_type: "Ride",
    workout_type: 0,
    id: 10175870177,
    start_date: "2023-11-07T09:51:39Z",
    start_date_local: "2023-11-07T10:51:39Z",
    timezone: "(GMT+01:00) Europe/Vienna",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 17,
    kudos_count: 5,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10175870177",
      summary_polyline:
        "ylfeHohscB|IfDfAr@bJfD|Bv@XjD_@rFEpJi@hFi@~Bw@tGSh@C|@eB|EtFxI|TvZBt@_AbB@TxA|BzBbFnDxDfCjAbJj@jDj@VGLm@j@o@`@FRvAuBlEBb@n@jBxEhIVbASf@gCzBi@lAeAjAiAhBUv@oC|DkA`CsAtFE`AkArFe@bGiApCyDnG}HxKaBfDiB|Ak@tAoAvFwCbE_JjOoA`AqF|BqB|AqBdCwAvDiB~M_@~@c@NOd@FvAd@\\?ZQBMc@XDG`@MGBa@^BZzAv@`Ar@rBt@LT~@^\\hAlC|BlDdApAEh@H^lB`Cl@`CZxFEo@WbAFLnAb@~@?lBv@jA`AnC|EVJnA~BfClBtAvDdAlAF^Cl@qCtFaGzN?T]^k@jAOt@eCzFMp@aB~C_CbG_@f@Q@MWYTj@?CZcFpLcBfDyCtH]vA}A~CS~@iAhBk@|AMz@_@TmAfCkAbDiGhN}DfL_D|FiAdD_BxCe@|AWTqCjH}@zAcAxCgCpFMBYm@a@[iDc@s@HW_@w@z@i@hB\\bBfBr@HbAM|ALx@iB~CJ@QBSd@@`AVVIh@Fn@t@j@k@tABz@ONLjAFIGi@ALe@Ge@PEb@e@JKr@^`Aa@hAdBjCFj@\\f@Nx@v@|AGKPCbApBTNCMr@c@NFPZBh@?YEYYg@k@l@WnAa@h@@TY\\?|Aw@nBBN|AtA\\lA`At@Xv@GNTXh@D`@b@bBJNb@nA|@|AzCVAf@i@PFHr@r@v@RlBn@xAKVVv@|@VMj@OjDVKfC~@Bf@`@{BLwCP{JAaEf@XjA?`F|@rAj@|@CZaAlBhCnA|@`BrBv@RbA|@pG`HVMGSb@a@rAPbAYTk@DwA`B}BkBfC]H[h@g@LQv@eADe@~@hB~AlGvGfAfBpAlA?PpBrAl@z@\\Jn@~@X`AN`Cb@hBWf@Ix@Wb@WhA[~AKv@Lz@SPe@a@a@jBCr@s@`BBbDYtBSNKj@[dDa@nC[dAMhCq@xCObB]~@[ZM`AqF`IuApAA^e@n@yBhCu@d@wA|B_JiBmCu@aDYuAm@sBGuDeA}AGcB{@BO_@]Gm@Mi@u@}@OcAKOc@IsAyEu@kBSMYsAaAuB_AsDe@q@UeAaCkHa@q@c@qCs@{A`Aw@INZKWC",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [48.20951865054667, 16.489002713933587],
    end_latlng: [48.216019654646516, 16.3723003026098],
    average_speed: 3.247,
    max_speed: 11.262,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 180.1,
    elev_low: 154.5,
    upload_id: 10898962124,
    upload_id_str: "10898962124",
    external_id: "D27D66FD-C8CE-4122-9922-E46E59EBE183-activity.fit",
    from_accepted_tag: false,
    pr_count: 5,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Hohe Wand climbing 🧗 🧗‍♂️",
    distance: 0.0,
    moving_time: 14400,
    elapsed_time: 14400,
    total_elevation_gain: 0,
    type: "RockClimbing",
    sport_type: "RockClimbing",
    id: 10171537923,
    start_date: "2023-11-06T11:30:00Z",
    start_date_local: "2023-11-06T12:30:00Z",
    timezone: "(GMT+01:00) Europe/Budapest",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 4,
    comment_count: 2,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10171537923",
      summary_polyline: "",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [],
    end_latlng: [],
    average_speed: 0.0,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    upload_id: null,
    external_id: null,
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Gumpoldskirchen with the British",
    distance: 3021.8,
    moving_time: 2604,
    elapsed_time: 5291,
    total_elevation_gain: 30.0,
    type: "Walk",
    sport_type: "Walk",
    id: 10167613843,
    start_date: "2023-11-05T14:25:44Z",
    start_date_local: "2023-11-05T15:25:44Z",
    timezone: "(GMT+01:00) Europe/Vienna",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 3,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10167613843",
      summary_polyline:
        "glfdHkoibBEEEXKXMLK^INKZEHAJ@Fd@`@PH`@j@L\\PVbAvBv@j@RJVTRJ`@XDN@TC?AEBDMJ@RACB?EAGe@A{@Ac@CADE@ZCY@ABB?B@QAFGKCA?DOMC\\BF@EHA@H@CABNEHOHFEB?FBCCBAE@A@HEGCIC@?@EIEMKGCFNH?DB@AH?KFHAD@DCAFFOIEB?CI?NMBG@HEC?LBJ@CA??CDAIBQCBEAAD?FHAC`@RRBI@MCWUIQB@DZJh@FLFTCR@KHKp@l@FKFDTN^^^f@|@lBH^`@fB~@bFJ^Hv@LXJN^^d@j@`Ar@tBnB^`@vBdBZ^v@n@Z^d@`@XPPPm@e@EEAK]MMKOQSSSU_@W_Ay@m@o@g@]qCkC}@s@s@u@S_@So@SeA[uBMc@UcBc@aBAQDCB@XR@BEAGCMOUEo@sA}@mA[QUCa@c@aAs@e@e@[Ka@[WYQ_@",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [48.0423476267606, 16.274372516199946],
    end_latlng: [48.04332420229912, 16.27450704574585],
    average_speed: 1.16,
    max_speed: 6.334,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 272.8,
    elev_low: 248.4,
    upload_id: 10890305266,
    upload_id_str: "10890305266",
    external_id: "garmin_ping_303257253666",
    from_accepted_tag: true,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Peilstein with the British",
    distance: 4765.7,
    moving_time: 4648,
    elapsed_time: 11397,
    total_elevation_gain: 276.0,
    type: "Walk",
    sport_type: "Walk",
    id: 10167612861,
    start_date: "2023-11-05T10:41:31Z",
    start_date_local: "2023-11-05T11:41:31Z",
    timezone: "(GMT+01:00) Europe/Vienna",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 4,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10167612861",
      summary_polyline:
        "ogbdHas_aBRRZN@FX@RF@LDFF?BJJFLXCPBTN?C?@BL@HNLBJPNJPAJDCFHNHF?DBBF?HHd@RHHCLPh@B@@ZJv@CNDF@PFBHT@ZHb@VNZd@Bn@FLLNP\\TB^h@FHAJDNPDJTNL`@h@VN^h@JB@HPXN\\HJNJPd@NP@HZ^n@\\?FFDXFHH\\?JCFBNTA@BBAHPRR`@b@@JH@HHH@ATZJB^\\FDH@NNL@TJPTh@Pf@Vb@t@EEC@l@JDK?O@AAC@JRHQDBBG??DACDF?H?CB@?@GMDNGWFLGMHLGG@BAAB@?CG?@H@?c@kAp@nAGG@?FP{@sADZ`@JBH?FAA?WAODF@ZGN?NHT@PENB@FA?@B?Bb@FZAh@Kz@]t@G\\C?HIDAF@JPNLAFF`@ALG@J?JAJF@BABHDBJD?HNFBNNTOXMHHFd@DB@DPTFN@h@Ab@DHJHT\\ALH^?G@@?HEKAKNOFCH?BEB?DJDB?CBALF?HDDRCDEHDFNBT@^BJEBAFEA@DCB@h@GFB@CEE@CBGPEBCYQECR?PEBEAAICAABBBG@CGK?MYa@[GUA@S]OEE@YUKAIDIIS?OMOYKMIECECBI[GGCMMK?EIMIEk@kAGBACWECFGAU]KBWEWBAAG@KEU@GCg@A[SK?MCEGOEODECq@AECCBCEKDK?IAu@o@IMWSAIQQOCEGIAKMCKo@MEDK?QKIOABEEQIOQE?SMYGGDKCYF_@@Wa@SQQ_@GWEESa@GCAGIGCKO]CSMUEWEI?CCIIEA@GEQESCi@QWAUEACU?SD]EW@WEk@@IDCAQMi@m@?KJk@@U?SKq@S|@]BNkAJKCDB@AFKRMDYZ?CBGb@c@DHTWIh@EEM@aA~CFm@Ta@ADIIAF?AEF?AA?ADDQ?BEC@E?@DCHDtA}GQfANOQr@[XVR@ED@Ff@GD]_@?SBEL?APFMANQPXb@F^MEHiAw@bKu@n@dAgI@HVN?a@IaBk@Lf@FFI@LUXD@JABCUk@RECFJEA@DYA]EMAa@EW@o@G_ABMGOKu@e@eAg@u@ESYe@c@k@_@q@Y{@S_@AMMS",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [48.024529963731766, 16.060832887887955],
    end_latlng: [48.02457723766565, 16.060851495712996],
    average_speed: 1.025,
    max_speed: 5.075,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 753.4,
    elev_low: 588.2,
    upload_id: 10890304206,
    upload_id_str: "10890304206",
    external_id: "garmin_ping_303238244524",
    from_accepted_tag: true,
    pr_count: 0,
    total_photo_count: 3,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Waiting for the British 🇬🇧",
    distance: 5718.5,
    moving_time: 1863,
    elapsed_time: 1900,
    total_elevation_gain: 4.2,
    type: "Run",
    sport_type: "Run",
    workout_type: 0,
    id: 10157280062,
    start_date: "2023-11-04T09:27:58Z",
    start_date_local: "2023-11-04T10:27:58Z",
    timezone: "(GMT+01:00) Europe/Vienna",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 8,
    kudos_count: 3,
    comment_count: 1,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10157280062",
      summary_polyline:
        "qckeHukxcBEUDcA?SCEBg@As@De@AWBMAM@u@BW?_@H_AFUHAXHBF\\FFDH@FHTBJJZJJ@PDZDLJNBPLF@BANH@AD@ZTJ@LFDAFHJ?BDXFFFJ?ZLJ@FFr@TJHHBDCPNR@TPHAb@RN@ZJBDBAZPTBNHVFTL^HHFTDHFNBBBDAL@RJXFJHFCHKDo@BEHe@DEH?JJHDF?JBL@HAFg@CIC[BUAc@Dc@AWDE@IBq@E{@FM?OAi@HE^PBFJHXBDDL?JFFCPLJ@XPJDF?LLP?n@Xd@FLFF?t@V^BHBDFH?FHDEFFN?HBFHJBD?PFL?h@TH?PLPBBFDAPDJAF@TLb@LL?JHH?JDJA?JF?PHXBZJTLT@x@T^Rf@Jb@DVNRDJ?r@XLCTNFBF?NJR?LH\\DNLL@HJAj@@NAVDZ@VDLCHD@BFANBh@CNDPId@DVCRDx@O~AKFG?IGOOg@Ia@UK?ICiAo@e@IIIe@KGCK?q@[SGKAKGSEaA]UCGGMGa@Ic@@QJKLI@IFq@zACBGTC@ENMLMXAT?VCTGJIDO^UTaA|Am@p@?HBLD@Xp@BNNTBPHFNZJJPj@R^DTa@rCENG~@Qz@Cf@Ib@Bj@CJIN?HDHHDVABDPBFB\\?DE\\VN?BDRFBFCPHR?PAFCAOp@M`BWhB?FGV?`@GFE`@Qx@Ar@Od@INKjAAHGHGb@ARGJIh@GJMh@GRGZK^Ep@Ar@CDBNStAIbAOb@QFEDA\\ILCNE@Eh@IXCD?PETAj@IZ@PQdA?d@Mr@AR@VGRIAIQSQCGOQCGQIE?CGIGg@UEFG|@[d@GVI?GDAHMRI^?PEH?HG`@?\\KXCDGAII_@IOIOCKGGBCE[Qk@OWQO?WOKACGYGE?_@Mk@MQKE?EEo@SWMSGIGa@C_@OSCKGk@OIIYEKGa@KECGAQIG?MGCEGCUISAEGQCo@SIIMEM?IK[KGGG?EEWC_@KQKWCSYA[b@_BB[p@{CB_@HQHu@JULu@A[LcAFu@BKDMHGl@TL?BDLDNLN@FI?cACm@@g@Aq@Ei@DU?WCI",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [48.23070013895631, 16.512664072215557],
    end_latlng: [48.229305474087596, 16.507828049361706],
    average_speed: 3.07,
    max_speed: 5.13,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 160.8,
    elev_low: 155.5,
    upload_id: 10879449345,
    upload_id_str: "10879449345",
    external_id: "27F06457-D485-4019-9D5F-25371D3FF43A-activity.fit",
    from_accepted_tag: false,
    pr_count: 2,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Board climbing",
    distance: 0.0,
    moving_time: 5400,
    elapsed_time: 5400,
    total_elevation_gain: 0,
    type: "RockClimbing",
    sport_type: "RockClimbing",
    id: 10148456453,
    start_date: "2023-11-02T14:30:00Z",
    start_date_local: "2023-11-02T15:30:00Z",
    timezone: "(GMT+01:00) Europe/Budapest",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 3,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10148456453",
      summary_polyline: "",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [],
    end_latlng: [],
    average_speed: 0.0,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    upload_id: null,
    external_id: null,
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "For the Krapfen 😎",
    distance: 4317.8,
    moving_time: 1432,
    elapsed_time: 1675,
    total_elevation_gain: 10.4,
    type: "Run",
    sport_type: "Run",
    workout_type: 0,
    id: 10140841089,
    start_date: "2023-11-01T09:36:03Z",
    start_date_local: "2023-11-01T10:36:03Z",
    timezone: "(GMT+01:00) Europe/Vienna",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 1,
    kudos_count: 6,
    comment_count: 3,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10140841089",
      summary_polyline:
        "i{jeHcaxcB]Ds@EO@GEODg@BEDU@MJC?GFMDEFMFIVQVKHQ^MNAHMXGXMTI`@IRKFCHG`@OREVGNIx@GVKlA@PMbA@LGR?VCN?p@GZ@LE~@ET@FEf@@d@GNBp@C^B\\Cr@BFAp@D~A?PETJn@?\\Fd@ALLx@FXHR@d@VjANZB`@HJ@NHJZnATb@LZFH@HZd@@HR^RTHRX^HFNTF?FLVVVZHDBABDNBHHFA`@RBDZLPD`@PPBLDD?b@NRAPFDAT@LBP?BB`@AN@ZCd@AHC^ANG^AHApA?FLBb@DJF\\HHFP@RDBZpA\\pB?JLV@l@Tb@FFHFPBFFBTDJB\\FLFFLnAHT@l@NDDDTFPL`@Hj@d@VDBF@TJHj@Nb@RVBf@Vf@NZN^FTFb@VJ?HFH?NJP@RLHD@CrAf@J?JBBDF?FEDKJoBVkBBe@DC?QCG@ICMIMCGAqAJq@BI@WDU?MNmA@YFUCGLaAJsADM@i@IKE@YQOCEE[MIAOKQ?CGMDAGE?CIU@ICU@IGIQMEy@?QIM@a@GEEGACEE@IIEWIO@WKc@B_@CEAQ\\mBFMPQ@UTa@H@FJ?PCD?FHBTRDNJFN^LLHDJ?D?HIFIBMBAHBDEN[FYJ]@IJEBE@]Fa@?YAOFu@@_@H_ADKBw@A]BOBc@Nw@BUJOHED@BE?OD_@CQJUHe@FkADQ@a@GQ?KOKI?MIGOUQSACGO?KGE?CBSAMMO?GGGAKOKGKHOKGOE@KCIK?KIAGDE?OIIFCJEDODSICa@IGU@KFIIS@QUWAUGQUKC",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [48.22852151468396, 16.512132911011577],
    end_latlng: [48.22628061287105, 16.51073371991515],
    average_speed: 3.015,
    max_speed: 4.358,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 160.8,
    elev_low: 155.4,
    upload_id: 10862198814,
    upload_id_str: "10862198814",
    external_id: "FAEEE725-703D-47AC-824D-49FAC30C790C-activity.fit",
    from_accepted_tag: false,
    pr_count: 1,
    total_photo_count: 1,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 34057799,
      resource_state: 1,
    },
    name: "Board climbing with new shoes 👞",
    distance: 0.0,
    moving_time: 7200,
    elapsed_time: 7200,
    total_elevation_gain: 0,
    type: "RockClimbing",
    sport_type: "RockClimbing",
    id: 10140099118,
    start_date: "2023-10-31T17:00:00Z",
    start_date_local: "2023-10-31T18:00:00Z",
    timezone: "(GMT+01:00) Europe/Budapest",
    utc_offset: 3600.0,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 3,
    comment_count: 1,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10140099118",
      summary_polyline: "",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [],
    end_latlng: [],
    average_speed: 0.0,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    upload_id: null,
    external_id: null,
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 1,
    has_kudoed: false,
  },
];
